from_latest_tag = false
ignore_merge_commits = false
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = [
  "cargo set-version {{version}} --package {{package}}",
  "cargo build"
]
post_package_bump_hooks = []
tag_prefix = "v"

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
kitty-remote-bindings = { path = "lib", changelog_path = "CHANGELOG.md" }
kitty-remote-bindings-macros = { path = "macros" }
