[package]
name = "kitty-remote-bindings-core"
version = "0.1.0"
description = "Internal core package of the kitty-remote-bindings crate"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

[dev-dependencies]
